### PR TITLE
option to skip discarded tabs

### PR DESCRIPTION
**Pull request by amandamana**
I haven't tested storing and loading the new preference as FireFox seems to prevent temporary add-ons from saving options to permanent storage.
EDIT: it works. I forgot to click 'Save Options'

### CODE REVIEW

**Comment by joshuacant** [comment]
Awesome! Thanks for making a PR!

I'll check this out, run it myself for a day or two (I always do this before a new version), then merge and post a new version to AMO.

**Comment by amandamana** [comment]
Sounds great, thanks! I've tested all combinations of the 3 options (skip collapsed, skip discarded, and skip cycling) in various positions and states of the tree.

**Comment by amandamana** [comment]
that was the definitely the last commit for issue #21 I plan to make a new pull request for issue #4 at some time in the future, perhaps next month.

**Comment by amandamana** [comment]
Guess I was wrong about being the last commit. This was only a one-liner so might as well put in here now :)

**Pull request merged**
