### PR TITLE
Code Refactor/Potential scroll bug fix

### PR DESCRIPTION
**Pull request by AllenAnthes**
First of all, I really appreciate you taking the time to port this over.  TST and this extension have really become an essential part of my workflow.

For the past few weeks it seemed like the scrolling functionality would quit working more often so I figured I'd poke around the code a bit.  Like yourself I've never worked with WebExtensions before and I've only played around with JavaScript, I primarily work with Java and Python.

In an attempt to isolate the bug I started modularizing stuff and pulling bits of code into separate functions.  I'm thinking the issue might have something to do with TST requiring a return value when it sends a `scrolled` message.  See:

> You must return any non-undefined value (including false, 0, and so on) from the listener. Otherwise TST guesses the listener addon is already unloaded and unlocks the scroll for your addon automatically.

That being said I was never able to actually prove it,  and I saw your function should have been returning a Promise at the end of the `case 'scrolled':`.  So.... ¯\\\_(ツ)_/¯, but it appears to be working now.  I was going to continue testing it but I figured I'd shoot it over to you to get your thoughts.

### CODE REVIEW

**Comment by AllenAnthes** [comment]
Implemented window scrolling functionality requested in issue #5 along with associated options

Figured I'd have it default to being off so it didn't surprise anyone.

**Comment by joshuacant** [comment]
This is wonderful, thank you so much for the contributions. I am going to give them a look over when I have a few minutes. It all sounds very good. I've had my own thoughts on fixing the "stops working" issue, but haven't had time to actually do anything about it. I pulled in a possible fix from another TST addon, but it didn't really fix the problem, and that author actually implemented the solution I had come up with previously (that also wasn't 100%). I look forward to giving this all a whirl and hopefully the issue can be fixed for good.

**Comment by joshuacant** [comment]
I love the changes. I've never been great about writing "good" code the first time, doubly so when learning new things. This refactor is something I'd have on my wishlist forever and never actually get around to doing. Thank you.

Now, speaking about the registration/re-registration issues, I'm still not seeing what I *think* should be the right behavior. If you look at the TST API docs, here: https://github.com/piroor/treestyletab/wiki/API-for-other-addons#register-and-unregister-your-addon-to-tst

My reading of that makes it sound like this should happen:
1. Install TST and my addon, in that order. Verify scrolling works.
2. Disable TST addon, from about:addons.
3. Enable TST addon.
4. TST sends 'ready' and my addon re-registers and scrolling works.

Instead, you get:
4. TST sends 'ready' and my addon re-registers (i guess?) but scrolling doesn't work anymore.

I added some debug statements to the [re]registration code, so take a look if you want. Seems like it should work, but does not, at least in my limited testing so far today. I have a couple thoughts I want to test, but ran out of time this morning. Hopefully later this week...

**Comment by AllenAnthes** [comment]
Can confirm, seeing the same thing under those conditions.  I've found that even after receiving and responding to our re-register event we're not being added back to the configs.cachedExternalAddons array.  Tomorrow I'm going to do a bit more digging into this, I have a feeling that that cache is where tst is storing what addons to send broadcasts to.  If that ends up being true it might not actually be a bug on our side. 

Normal operations:
image

After disable/enable TST.
image

Initialization and attempt to re-register after disabling/enabling TST
image

**Comment by joshuacant** [comment]
I've been reluctant to open a ticket with Piro until I was SURE that the problem was on his end. If you dig up some actionable info, open an issue with him and reference this thread. Otherwise hopefully we can figure out where I'm going wrong.

**Pull request merged**
